declare module '@gmod/cram'
declare module '@jbrowse/core/util/offscreenCanvasPonyfill'
declare module '@jbrowse/core/util/QuickLRU'
declare module 'json-stable-stringify'
declare module 'd3-scale'
declare module 'react-d3-axis'